name: Release Image

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 下载 Artifact
        uses: actions/download-artifact@v3
        with:
          name: debian-12-custom.qcow2

      - name: 发布到 GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: debian-12-custom.qcow2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
